# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# The following parameters are used by "stack new" to automatically fill fields
# in the cabal config. We recommend uncommenting them and filling them out if
# you intend to use 'stack new'.
# See https://docs.haskellstack.org/en/stable/yaml_configuration/#templates
templates:
  params:
    author-name:     "Valentin Robert"
    #author-email:    "valentin.robert.42@gmail.com"
    github-username: "Ptival"
    #copyright:
nix:
  enable: true
  packages:
    - pkgconfig
    - zlib
  # Currently using a modified ghc844 derivation, so overriding the path
  # path: [nixpkgs=/Users/val/nixpkgs]
  path: [nixpkgs=/Users/val/.nix-defexpr/channels/nixpkgs]
  # Without this flag, stack will start ghci in a pure environment, whose
  # locale gets reset from the lovely UTF-8 to the sad ASCII. This makes
  # ghci unable to handle Unicode in input and output, and, as a result,
  # intero fails to report any error message involving Unicode characters.
  pure: false
